src/CtrlBox.UI.Web/Controllers/RouteController.cs
using System;
using System.Linq;
using CtrlBox.Application.ViewModel;
using CtrlBox.Domain.Interfaces.Application;
using CtrlBox.UI.Web.Helpers;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace CtrlBox.UI.Web.Controllers
{
    public class RouteController : Controller
    {
        private readonly IClientApplicationService _clientApplicationService;
        private readonly IRouteApplicationService _routeApplicationService;

        public RouteController(IClientApplicationService clientService, IRouteApplicationService routeService)
        {
            _clientApplicationService = clientService;
            _routeApplicationService = routeService;
        }

        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult AjaxHandlerGet()
        {
            var routesVMs = _routeApplicationService.GetAll();
            
            return Json(new
            {
                aaData = routesVMs,
                success = true
            });
        }

        public ActionResult Create(Guid routeID)
        {
            var routeVM = _routeApplicationService.GetById(routeID);

            var clients = _clientApplicationService.GetAll()
                                        .Select(client => new SelectListItem
                                        {
                                            Value = client.DT_RowId,
                                            Text = client.Name
                                        }).ToList();
            ViewData["Clients"] = clients;

            return View(routeVM);
        }

        [HttpPost]
        public ActionResult Create(RouteVM routeVM)
        {
            _routeApplicationService.Add(routeVM);
            var routesVMs = _routeApplicationService.GetAll();
           
            return View("Index", routesVMs);
        }

        [HttpPost]
        public ActionResult Edit(RouteVM routeVM)
        {
            _routeApplicationService.Update(routeVM);

            return Json(new
            {
                success = true,
                Message = "OK"
            });
        }


        public ActionResult ClientRelation(string linhaID)
        {
            //caso esta linha tenha alguma entrega pendente, não pode remover o cliente
            ViewData["routeID"] = linhaID;

            var routeVM = _routeApplicationService.GetById(new Guid(linhaID));
            
            return View(routeVM);
        }

        [HttpGet]
        public ActionResult GetAjaxHandlerClientsNotAvailable(string routeID)
        {
            try
            {
                var clientsVM = _clientApplicationService.GetNotAvailable(new Guid(routeID));

                return Json(new
                {
                    aaData = clientsVM,
                    success = true
                });
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        [HttpGet]
        public ActionResult GetAjaxHandlerClientsAvailable(string routeID)
        {
            try
            {
                var clientsVM = _clientApplicationService.GetAvailable(new Guid(routeID));
               
                return Json(new
                {
                    aaData = clientsVM,
                    success = true
                });
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        [HttpPost]
        public ActionResult PutAjaxHandlerAddClients(string[] clientsIDs)
        {
            try
            {
                JsonSerialize jsonS = new JsonSerialize();
                var routeClientVM = jsonS.JsonDeserialize<RouteClientVM>(clientsIDs[0]);

                _routeApplicationService.ConnectRouteToClient(routeClientVM);

                return Json(new
                {
                    success = true,
                    Message = "OK"
                });
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        [HttpPost]
        public ActionResult PutAjaxHandlerRemoveClients(string[] clientsIDs)
        {
            try
            {
                JsonSerialize jsonS = new JsonSerialize();
                var routeClientVM = jsonS.JsonDeserialize<RouteClientVM>(clientsIDs[0]);

                _routeApplicationService.RemoveRouteFromClient(routeClientVM);

                return Json(new
                {
                    success = true,
                    Message = "OK"
                });
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }
    }
}

src/CtrlBox.UI.Web/Views/Route/ClientRelation.cshtml
@model CtrlBox.Application.ViewModel.RouteVM

@{
    ViewData["Title"] = "Home Page";
}
@section scriptsViews
    {
    <partial name="~/Views/PartialsSections/_ScriptsTable.cshtml" />
}
<script type="text/javascript">
    @{
                var routeID = ViewData["routeID"];
            }

    var _routeID = '@routeID';

    function loadTable(id, url) {

        var oTable = $(id).dataTable({
            "sAjaxSource": url,
            "bProcessing": true,
            "bDestroy": true,
            "aoColumns": [
                            {
                                "mData": "Name"
                            },
                            {
                                "mData": "Address"
                            },
                            {
                                "mData": "Phone"
                            },
                            {
                                "mData": null,
                                "sType": "html",
                                "mRender": function (data, type, row) {
                                    if (type === 'display') {
                                        return '<input type="checkbox" name="ClientID" value="' + row.DT_RowId + '">';
                                    }
                                    return data;
                                }
                            }
            ],
            "aLengthMenu": [
                [5, 15, 20, -1],
                [5, 15, 20, "All"] // change per page values here
            ],
            // set the initial value
            "iDisplayLength": 5,
            "sDom": "<'row-fluid'<'span6'l><'span6'f>r>t<'row-fluid'<'span6'i><'span6'p>>",
            "sPaginationType": "bootstrap",
            "oLanguage": {
                "sLengthMenu": "_MENU_ records per page",
                "oPaginate": {
                    "sPrevious": "Prev",
                    "sNext": "Next"
                }
            },
            "aoColumnDefs": [{
                'bSortable': false,
                'aTargets': [0]
            }
            ]
        });

        return oTable;
    }

    function loadTables() {

        var urlCustomersAvailable = '@Url.Content("~/Route/GetAjaxHandlerClientsAvailable")?routeID=' + '@routeID';
        loadTable('#tbAdd', urlCustomersAvailable);

        var urlCustomersNotAvailable = '@Url.Content("~/Route/GetAjaxHandlerClientsNotAvailable")?routeID=' + '@routeID';
        loadTable('#tbRemove', urlCustomersNotAvailable);
    }

    (function ($) {
        $.fn.serializeFormJSON = function () {
            var lista = [];
            var a = this.serializeArray();
            $.each(a, function () {
                lista.push({ "ClientID": this.value, "RouteID": '@routeID' });
            });
            return JSON.stringify(lista);
        };
    })(jQuery);

    jQuery(document).ready(function () {
        loadTables();

        $('#btnSubmitAdd').click(function () {
            var oTableAdd = $('#tbAdd').dataTable();
            var sData = $(oTableAdd.$("input[name='ClientID']:checked")).serializeFormJSON();

            $.ajax({
                url: '@Url.Content("~/Route/PutAjaxHandlerAddClients")',
                type: 'POST',
                dataType: 'json',
                data: { clientsIDs: sData },
                "success": function (json) {
                    if (!json.NotAuthorized) {
                        alert('Complete');
                        loadTables();
                    }
                },
                "error": handleAjaxError
            });

           return false;
        });

        $('#btnSubmitRemove').click(function () {
            var oTableRemove = $('#tbRemove').dataTable();
            var sData = $(oTableRemove.$("input[name='ClientID']:checked")).serializeFormJSON();

            $.ajax({
                url: '@Url.Content("~/Route/PutAjaxHandlerRemoveClients")',
                type: 'POST',
                dataType: 'json',
                data: { clientsIDs: sData },
                "success": function (json) {
                    if (!json.NotAuthorized) {
                        alert('Complete');
                        loadTables();
                    }
                },
                "error": handleAjaxError
            });
            return false;
        });
    });
</script>

<div class="page-content">
    <!-- BEGIN PAGE CONTAINER-->
    <div class="container-fluid">
        <!-- BEGIN PAGE HEADER-->
        <div class="row-fluid">
            <div class="span12">
                <!-- BEGIN PAGE TITLE & BREADCRUMB-->
                <ul class="breadcrumb">
                    <li>
                        <i class="icon-home"></i>
                        <a href="index.html">Route</a>
                        <i class="icon-angle-right"></i>
                    </li>
                    <li>
                        <a href="#">Route list</a>
                        <i class="icon-angle-right"></i>
                    </li>
                    <li><a href="#">Link route to clients</a></li>
                </ul>
                <!-- END PAGE TITLE & BREADCRUMB-->
            </div>
        </div>
        <!-- END PAGE HEADER-->
        <!-- BEGIN PAGE CONTENT-->
        <div class="row-fluid">
            <div class="span12">
                <div class="alert alert-info">
                    <h3><strong>Route name:</strong> @Model.Name</h3>
                </div>
            </div>
        </div>
        <div class="row-fluid">
            <div class="span6">
                <!-- BEGIN SAMPLE TABLE PORTLET-->
                <div class="portlet box green">
                    <div class="portlet-title">
                        <div class="caption"><i class="icon-cogs"></i>Clientes disponíveis</div>

                    </div>
                    <div class="portlet-body">
                        <form id="form">
                            <table id="tbAdd" class="table-bordered table-striped table-condensed cf">
                            <thead class="cf">
                                    <tr>
                                        <th>Nome</th>

                                        <th class="hidden-480">Telefone</th>
                                        <th>Telefone</th>
                                        <th>Vender</th>

                                    </tr>
                                </thead>
                                <tbody></tbody>
                            </table>
                        </form>
                        <a href="#" id="btnSubmitAdd" class="btn green"><i class="icon-plus"></i> Adicionar</a>

                    </div>
                </div>
                <!-- END SAMPLE TABLE PORTLET-->

            </div>
            <div class="span6">
                <!-- BEGIN SAMPLE TABLE PORTLET-->
                <div class="portlet box red">
                    <div class="portlet-title">
                        <div class="caption"><i class="icon-cogs"></i>Clientes desta linha</div>

                    </div>
                    <div class="portlet-body">
                        <form id="form">
                            <table id="tbRemove" class="table-bordered table-striped table-condensed cf">
                            <thead class="cf">
                                    <tr>
                                        <th>Nome</th>

                                        <th class="hidden-480">Telefone</th>
                                        <th>Telefone</th>
                                        <th>Vender</th>

                                    </tr>
                                </thead>
                                <tbody></tbody>
                            </table>
                        </form>
                        @if (!Model.HasOpenDelivery)
                        {
                            <a href="#" id="btnSubmitRemove" class="btn red"><i class="icon-trash"></i> Remover</a>
                        }
                        else
                        {
                            <div class="alert">

                                <strong>Warning!</strong> Existe uma entrega em aberto.
                            </div>
                        }
                    </div>
                </div>
                <!-- END SAMPLE TABLE PORTLET-->

            </div>
        </div>
        <div class="row-fluid">
            <div class="span12">
                <a onclick="window.history.back(); return false;" href="#" class="btn purple"><i class="m-icon-swapleft  m-icon-white"></i> Back</a>

            </div>
        </div>

        <!-- END PAGE CONTENT-->
    </div>
    <!-- END PAGE CONTAINER-->
</div>

src/CtrlBox.UI.Web/Views/Route/Create.cshtml
@model CtrlBox.Application.ViewModel.RouteVM

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@section cssViews{
    <!-- BEGIN PAGE LEVEL STYLES -->
    <link rel="stylesheet" type="text/css" href="~/plugins/select2/select2_metro.css" />

    <!-- END PAGE LEVEL STYLES -->
}
@section scriptsViews{
    <!-- BEGIN PAGE LEVEL PLUGINS -->
    <script type="text/javascript" src="~/plugins/select2/select2.min.js"></script>
    <!-- END PAGE LEVEL PLUGINS -->
}

<script type="text/javascript">
    jQuery(document).ready(function () {
        $('.select2_option').select2({
            allowClear: true
        });
    });
</script>
<div class="page-content">
    <!-- BEGIN PAGE CONTAINER-->
    <div class="container-fluid">
        <!-- BEGIN PAGE HEADER-->
        <div class="row-fluid">
            <div class="span12">
                <ul class="breadcrumb">
                    <li>
                        <i class="icon-home"></i>
                        <a href="index.html">Client</a>
                        <span class="icon-angle-right"></span>
                    </li>
                    <li>
                        <a href="#">Index</a>
                        <span class="icon-angle-right"></span>
                    </li>
                    <li><a href="#">Create</a></li>
                </ul>
            </div>
        </div>
        <!-- END PAGE HEADER-->
        <!-- BEGIN PAGE CONTENT-->
        <div class="row-fluid">
            <div class="span12">
                <div class="portlet box blue">
                    <div class="portlet-title">
                        <div class="caption"><i class="icon-plus"></i>Create</div>
                    </div>
                    <div class="portlet-body">
                        <!-- BEGIN FORM-->
                        <form asp-action="Create" asp-controller="Route" class="form-horizontal">
                            <input type="hidden" asp-for="DT_RowId" />
                            <div class="control-group">
                                <label class="control-label">Name</label>
                                <div class="controls">
                                    <input type="text" name="Name" placeholder="Name" asp-for="Name" class="m-wrap large" />
                                    <span class="help-inline">Name</span>
                                </div>
                            </div>
                            <div class="control-group">
                                <label class="control-label">KmDistance</label>
                                <div class="controls">
                                    <input type="text" name="KmDistance" placeholder="KmDistance" asp-for="KmDistance" class="m-wrap large" />
                                    <span class="help-inline">KmDistance</span>
                                </div>
                            </div>
                            <div class="control-group">
                                <label class="control-label">Truck</label>
                                <div class="controls">
                                    <input type="text" name="Truck" placeholder="Truck" asp-for="Truck" class="m-wrap large" />
                                    <span class="help-inline">Truck</span>
                                </div>
                            </div>
                            <div class="control-group">
                                <label class="control-label">Client origin</label>
                                <div class="controls">
                                    <select id="ddlClient" class="span6 select2_option" data-placeholder="Choose a Client" name="ClientOriginID" asp-for="ClientOriginID" asp-items="@((List<SelectListItem>)ViewData["Clients"])"></select>
                                </div>
                            </div>
                            <div class="form-actions">
                                <button type="submit" class="btn blue"><i class="icon-ok"></i> Save</button>
                                <button type="button" class="btn">Cancel</button>
                            </div>
                        </form>
                        <!-- END FORM-->
                    </div>
                </div>
            </div>
        </div>
        <!-- END PAGE CONTENT-->
    </div>
    <!-- END PAGE CONTAINER-->
</div>

src/CtrlBox.UI.Web/Views/Route/Index.cshtml
@{
    ViewData["Title"] = "Routes";
}
@section scriptsViews
    {
    <partial name="~/Views/PartialsSections/_ScriptsTable.cshtml" />
}
<script src="~/scripts/tb-route.js"></script>

<script type="text/javascript">
    jQuery(document).ready(function () {
        var url = '@Url.Content("~/Route/AjaxHandlerGet")';

        TableEditable.init(url);
    });
</script>

@Html.Hidden("editUrl", Url.Action("Route/Index"))


<!-- BEGIN PAGE -->
<div class="page-content">
    <!-- BEGIN SAMPLE PORTLET CONFIGURATION MODAL FORM-->
    <div id="portlet-config" class="modal hide">
        <div class="modal-header">
            <button data-dismiss="modal" class="close" type="button"></button>
            <h3>portlet Settings</h3>
        </div>
        <div class="modal-body">
            <p>Here will be a configuration form</p>
        </div>
    </div>
    <!-- END SAMPLE PORTLET CONFIGURATION MODAL FORM-->
    <!-- BEGIN PAGE CONTAINER-->
    <div class="container-fluid">
        <!-- BEGIN PAGE HEADER-->
        <div class="row-fluid">
            <div class="span12">
                <!-- BEGIN PAGE TITLE & BREADCRUMB-->
                <ul class="breadcrumb">
                    <li>
                        <i class="icon-home"></i>
                        <a href="index.html">Route</a>
                        <i class="icon-angle-right"></i>
                    </li>
                    <li>
                        <a href="#">Index</a>
                    </li>
                </ul>
                <!-- END PAGE TITLE & BREADCRUMB-->
            </div>
        </div>
        <!-- END PAGE HEADER-->
        <!-- BEGIN PAGE CONTENT-->
        <div class="row-fluid">
            <div class="span12">
                <!-- BEGIN EXAMPLE TABLE PORTLET-->
                <div class="portlet box blue">
                    <div class="portlet-title">
                        <div class="caption"><i class="icon-edit"></i>List all routes</div>
                        <div class="actions">
                            <a asp-action="Create" class="btn purple easy-pie-chart-reload"><i class="icon-plus"></i> Add Route</a>
                        </div>
                    </div>
                    <div class="portlet-body no-more-tables">
                        <table class="table-bordered table-striped table-condensed cf" id="sample_editable_1">
                            <thead class="cf">
                                <tr>
                                    <th>Username</th>
                                    <th>KmDistance</th>
                                    <th>Truck</th>
                                    <th>HasOpenDelivery</th>
                                    <th>Edit</th>
                                    <th>Delete</th>
                                    <th>Options</th>
                                </tr>
                            </thead>
                            <tbody></tbody>
                        </table>
                    </div>
                </div>
                <!-- END EXAMPLE TABLE PORTLET-->
            </div>
        </div>
        <!-- END PAGE CONTENT -->
    </div>
    <!-- END PAGE CONTAINER-->
</div>
<!-- END PAGE -->