src/CtrlBox.UI.Web/Controllers/BoxController.cs
using CtrlBox.Application.ViewModel;
using CtrlBox.CrossCutting;
using CtrlBox.Domain.Interfaces.Application;
using CtrlBox.UI.Web.Helpers;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;

namespace CtrlBox.UI.Web.Controllers
{
    public class BoxController : Controller
    {
        private readonly IBoxApplicationService _boxApplicationService;
        private readonly IProductApplicationService _productApplicationService;
        private readonly IClientApplicationService _clientService;
        private readonly ITrackingApplicationService _trackingService;

        public BoxController(IBoxApplicationService boxApplicationService, IProductApplicationService productApplicationService,
                             IClientApplicationService clientService, ITrackingApplicationService trackingService)
        {
            _boxApplicationService = boxApplicationService;
            _productApplicationService = productApplicationService;
            _trackingService = trackingService;
            _clientService = clientService;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult GetAjaxHandlerBoxes()
        {
            try
            {
                var boxesVM = _boxApplicationService.GetAll();

                return Json(new
                {
                    aaData = boxesVM,
                    success = true
                });
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        public IActionResult Create()
        {
            var boxesType = _boxApplicationService.GetAllBoxesType()
                                                    .Select(boxType => new SelectListItem
                                                    {
                                                        Value = boxType.DT_RowId,
                                                        Text = $"{boxType.Name} - {boxType.Description}"
                                                    }).ToList();
            ViewData["BoxesType"] = boxesType;

            var products = _productApplicationService.GetAll()
                                        .Select(prod => new SelectListItem
                                        {
                                            Value = prod.DT_RowId,
                                            Text = $"{prod.Name} - {prod.Description} - {prod.Package} - {prod.Capacity}{prod.UnitMeasure}"
                                        }).ToList();
            ViewData["Products"] = products;

            var boxes = _boxApplicationService.GetBoxesParentsWithBoxTypeEndProduct()
                            .Select(box => new SelectListItem
                            {
                                Value = box.DT_RowId,
                                Text = $"{box.BoxBarcode.BarcodeEAN13} {box.Description}"
                            }).ToList();

            ViewData["Boxes"] = boxes;

            return View();
        }

        [HttpPost]
        public IActionResult Create(BoxVM boxVM)
        {
            try
            {
                _boxApplicationService.Add(boxVM);
                return RedirectToAction("Index");
            }
            catch (CustomException exc)
            {
                throw exc;
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        public IActionResult BoxesType()
        {
            return View();
        }

        [HttpGet]
        public IActionResult GetAjaxHandlerBoxesType()
        {
            try
            {
                var boxesTypVM = _boxApplicationService.GetAllBoxesType();

                return Json(new
                {
                    aaData = boxesTypVM,
                    success = true
                });
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        public IActionResult CreateBoxType()
        {
            var optionsBoxLengthUnit = CtrlBoxUnits.CtrlBoxLengthUnit
                   .Select(unit => new SelectListItem
                   {
                       Value = unit,
                       Text = unit
                   }).ToList();
            ViewData["OptionsBoxLengthUnit"] = optionsBoxLengthUnit;
            return View();
        }

        [HttpPost]
        public IActionResult CreateBoxType(BoxTypeVM boxTypeVM, IFormFile FilePicture)
        {
            try
            {
                PictureVM imageEntity = GeneratePicture.CreatePicture(FilePicture, $"{boxTypeVM.Name} - {boxTypeVM.Description}");
                boxTypeVM.Picture = imageEntity;

                _boxApplicationService.AddBoxType(boxTypeVM);

                return RedirectToAction("BoxesType");
            }
            catch (CustomException exc)
            {
                throw exc;
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        public IActionResult ViewBoxes(Guid boxFatherID)
        {
            var boxes = _boxApplicationService.GetBoxesByBoxWithChildren(boxFatherID);
            return View(boxes);
        }

        public IActionResult BoxStock()
        {
            var boxesType = _boxApplicationService.GetAllBoxesType()
                                        .Select(boxType => new SelectListItem
                                        {
                                            Value = boxType.DT_RowId,
                                            Text = $"{boxType.Name} - {boxType.Description}"
                                        }).ToList();
            ViewData["BoxesType"] = boxesType;

            var clients = _clientService.GetAll()
                                        .Select(client => new SelectListItem
                                        {
                                            Value = client.DT_RowId,
                                            Text = client.Name
                                        }).ToList();
            ViewData["Clients"] = clients;

            var products = _productApplicationService.GetAll()
                                        .Select(prod => new SelectListItem
                                        {
                                            Value = prod.DT_RowId,
                                            Text = $"{prod.Name} - {prod.Description} - {prod.Package} - {prod.Capacity}{prod.UnitMeasure}"
                                        }).ToList();
            ViewData["Products"] = products;

            var trackingsTypes = _trackingService.GetAllTrackingsTypesByPlace()
                                        .Select(trace => new SelectListItem
                                        {
                                            Value = trace.DT_RowId,
                                            Text = trace.Description
                                        }).ToList();
            ViewData["TrackingTypes"] = trackingsTypes;
            return Index();
        }

        [HttpGet]
        public IActionResult GetAjaxHandlerAvailableProductItemsByClientIDAndProductID(Guid productID, Guid clientID)
        {
            try
            {
                var productItems = _productApplicationService.GetAvailableStockProductItemsByClientIDAndProductID(productID, clientID);
                return Json(new
                {
                    aaData = productItems,
                    success = true
                });
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        [HttpGet]
        public IActionResult GetAjaxHandlerAvailableBoxesByBoxTypeIDAndProductID(Guid boxTypeID, Guid clientID)
        {
            try
            {
                var boxes = _productApplicationService.GetAvailableBoxesByBoxTypeIDAndProductID(boxTypeID, clientID);
                return Json(new
                {
                    aaData = boxes,
                    success = true
                });
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        [HttpPost]
        public IActionResult PostAjaxHandlerAddBoxStockWithBoxes(Guid boxTypeID, Guid trackingTypeID, Guid clientID, Guid boxTypeChildID, int quantity)
        {
            try
            {
                _productApplicationService.AddBoxStockWithBoxes(boxTypeID, trackingTypeID, clientID, boxTypeChildID, quantity);
                return Json(new
                {
                    success = true
                });
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        [HttpPost]
        public IActionResult PostAjaxHandlerAddBoxStockWithProductItems(Guid boxTypeID, Guid trackingTypeID, Guid clientID, Guid productID, int quantity)
        {
            try
            {
                _productApplicationService.AddBoxStockWithProductItems(boxTypeID, trackingTypeID, clientID, productID, quantity);
                return Json(new
                {
                    success = true
                });
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        public IActionResult GenerateBoxes(int nivel)
        {
            _boxApplicationService.GenarateBoxes(nivel);
            return RedirectToAction("Index");
        }

        public IActionResult GenerateProductItems()
        {
            _productApplicationService.GenerateProductItem(new Guid("45458722-5D7C-48F9-AE8D-96CDC4B31CE8"), 5040);
            return RedirectToAction("Index");
        }
    }
}

src/CtrlBox.UI.Web/Views/Box/BoxStock.cshtml
@{
    ViewData["Title"] = "BoxStock";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section cssViews{
    <!-- BEGIN PAGE LEVEL STYLES -->
    <link rel="stylesheet" type="text/css" href="~/plugins/select2/select2_metro.css" />

    <!-- END PAGE LEVEL STYLES -->
}
@section scriptsViews{
    <!-- BEGIN PAGE LEVEL PLUGINS -->
    <script type="text/javascript" src="~/plugins/select2/select2.min.js"></script>
    <script src="~/js/box-stock.js"></script>
    <!-- END PAGE LEVEL PLUGINS -->
}

<script type="text/javascript">
    jQuery(document).ready(function () {

        BoxStock.init();


    });
</script>
<!-- BEGIN PAGE -->
<div class="page-content" style="min-height:1029px !important">
    <!-- BEGIN PAGE CONTAINER-->
    <div class="container-fluid">
        <!-- BEGIN PAGE HEADER-->
        <div class="row-fluid">
            <div class="span12">
                <!-- BEGIN PAGE TITLE & BREADCRUMB-->
                <ul class="breadcrumb">
                    <li>
                        <i class="icon-home"></i>
                        <a href="index.html">Home</a>
                        <i class="icon-angle-right"></i>
                    </li>
                    <li>
                        <a href="#">Layouts</a>
                        <i class="icon-angle-right"></i>
                    </li>
                    <li><a href="#">Blank Page</a></li>
                </ul>
                <!-- END PAGE TITLE & BREADCRUMB-->
            </div>
        </div>
        <!-- END PAGE HEADER-->
        <!-- BEGIN PAGE CONTENT-->
        <div class="row-fluid">
            <div class="span12">
                <div class="portlet box blue">
                    <div class="portlet-title">
                        <div class="caption"><i class="icon-reorder"></i>Add stock box</div>
                    </div>
                    <div class="portlet-body form">
                        <h3 class="block">choose options</h3>
                        <!-- BEGIN FORM-->
                        <form action="#" class="form-horizontal">
                            <div class="control-group">
                                <label class="control-label">Create Box type</label>
                                <div class="controls">
                                    <select id="ddlBoxesType" class="span6 select2_option" data-placeholder="Choose a box type" tabindex="1" name="BoxTypeID" asp-items="@((List<SelectListItem>)ViewData["BoxesType"])"><option value="0">Please select box</option></select>
                                </div>
                            </div>
                            <div class="control-group">
                                <label class="control-label">Tracking Types</label>
                                <div class="controls">
                                    <select id="ddlTrackingType" class="span6 select2_option" data-placeholder="Choose a tracking Types" name="TrackingTypeID" asp-items="@((List<SelectListItem>)ViewData["TrackingTypes"])"><option value="0">Please select Tracking Types</option></select>
                                </div>
                            </div>
                            <div class="control-group">
                                <label class="control-label">Client</label>
                                <div class="controls">
                                    <select id="ddlClient" class="span6 select2_option" data-placeholder="Choose a Client" name="ClientID" asp-items="@((List<SelectListItem>)ViewData["Clients"])"></select>
                                </div>
                            </div>
                            <div class="control-group">
                                <label class="control-label">Which box child</label>
                                <div class="controls">
                                    <label class="radio">
                                        <input type="radio" id="idHasProduct" name="HasProduct" value="True" />
                                        Has Product
                                    </label>
                                    <label class="radio">
                                        <input type="radio" name="HasProduct" value="False" checked />
                                        Hasn't Product
                                    </label>
                                </div>
                            </div>
                            <div id="grpBoxesChild" class="control-group">
                                <label class="control-label">Box type child</label>
                                <div class="controls">
                                    <select id="ddlBoxesTypeChild" class="span6 select2_option" data-placeholder="Choose a box type" name="BoxesTypeChildID" asp-items="@((List<SelectListItem>)ViewData["BoxesType"])"><option value="0">Please select box</option></select>
                                </div>
                            </div>
                            <div id="grpProducts" style="display:none;" class="control-group">
                                <label class="control-label">Product</label>
                                <div class="controls">
                                    <select id="ddlProduct" class="span6 select2_option" data-placeholder="Choose a Product" name="ProductID" asp-items="@((List<SelectListItem>)ViewData["Products"])"><option value="0">Please select user</option></select>
                                </div>
                            </div>
                            <div class="control-group">
                                <label class="control-label">Available child</label>
                                <div class="controls">
                                    <input id="txtAvailableChild" class="span6 m-wrap" type="text" placeholder="" disabled="">
                                    <span class="help-inline">Total available child</span>
                                </div>
                            </div>
                            <div class="control-group">
                                <label class="control-label">Quantity</label>
                                <div class="controls">
                                    <input id="txtQuantity" type="text" class="span6 m-wrap">
                                    <span class="help-inline">Enter with total boxes</span>
                                </div>
                            </div>
                            <div class="form-actions">
                                <a onclick="window.history.back(); return false;" href="#" class="btn purple"><i class="m-icon-swapleft  m-icon-white"></i> Back</a>
                                <a onclick="window.history.back(); return false;" href="#" class="btn yellow"> Cancel</a>
                                <a href="#" id="btnSubmit" class="btn green"><i class="icon-plus"></i> Salvar</a>
                            </div>
                        </form>
                        <!-- END FORM-->
                    </div>
                </div>
            </div>
        </div>
        <!-- END PAGE CONTENT-->
    </div>
    <!-- END PAGE CONTAINER-->
</div>
<!-- END PAGE -->

src/CtrlBox.UI.Web/Views/Box/Create.cshtml
@model CtrlBox.Application.ViewModel.BoxVM

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section cssViews{
    <!-- BEGIN PAGE LEVEL STYLES -->
    <link rel="stylesheet" type="text/css" href="~/plugins/select2/select2_metro.css" />

    <!-- END PAGE LEVEL STYLES -->
}
@section scriptsViews{
    <!-- BEGIN PAGE LEVEL PLUGINS -->
    <script type="text/javascript" src="~/plugins/select2/select2.min.js"></script>
    <!-- END PAGE LEVEL PLUGINS -->
}

<script type="text/javascript">
    jQuery(document).ready(function () {
        $('.select2_option').select2({
            allowClear: true
        });

        $('.radio input[type=radio][name=HasProduct]').change(function () {
            var hasProduct = $(".radio input[type=radio][id=idHasProduct]").is(":checked");

            if (hasProduct) {
                $("#grpProducts").show();
                $("#grpBoxes").hide();
            } else {
                $("#grpProducts").hide();
                $("#grpBoxes").show();
            }
        });
    });
</script>
<div class="page-content">
    <!-- BEGIN PAGE CONTAINER-->
    <div class="container-fluid">
        <!-- BEGIN PAGE HEADER-->
        <div class="row-fluid">
            <div class="span12">
                <ul class="breadcrumb">
                    <li>
                        <i class="icon-home"></i>
                        <a href="index.html">Address</a>
                        <span class="icon-angle-right"></span>
                    </li>
                    <li>
                        <a href="#">Index</a>
                        <span class="icon-angle-right"></span>
                    </li>
                    <li><a href="#">Create</a></li>
                </ul>
            </div>
        </div>
        <!-- END PAGE HEADER-->
        <!-- BEGIN PAGE CONTENT-->
        <div class="row-fluid">
            <div class="span12">
                <div class="portlet box blue">
                    <div class="portlet-title">
                        <div class="caption"><i class="icon-plus"></i>Data load box</div>
                    </div>
                    <div class="portlet-body">
                        <!-- BEGIN FORM-->
                        <form asp-action="Create" asp-controller="Box" class="form-horizontal">
                            <div class="control-group">
                                <label class="control-label">Box type</label>
                                <div class="controls">
                                    <select id="ddlBoxesType" class="span6 select2_option" data-placeholder="Choose a box type" tabindex="1" name="BoxTypeID" asp-for="BoxTypeID" asp-items="@((List<SelectListItem>)ViewData["BoxesType"])"><option value="0">Please select box</option></select>
                                </div>
                            </div>
                            <div class="control-group">
                                <label class="control-label">Which box</label>
                                <div class="controls">
                                    <label class="radio">
                                        <input type="radio" id="idHasProduct" name="HasProduct" value="True" />
                                        Has Product
                                    </label>
                                    <label class="radio">
                                        <input type="radio" name="HasProduct" value="False" checked />
                                        Hasn't Product
                                    </label>
                                </div>
                            </div>
                            <div id="grpProducts" style="display:none">
                                <div class="control-group">
                                    <label class="control-label">Product</label>
                                    <div class="controls">
                                        <select class="span6 select2_option" data-placeholder="Choose a product" tabindex="1" name="ProductID" asp-for="ProductID" asp-items="@((List<SelectListItem>)ViewData["Products"])"><option value="0">Please select Product</option></select>
                                    </div>
                                </div>
                                <div class="control-group">
                                    <label class="control-label">Quantity product Items</label>
                                    <div class="controls">
                                        <input type="text" name="RangeProductsItems" placeholder="number" class="m-wrap medium" />
                                        <span class="help-inline">Range of the first available</span>
                                    </div>
                                </div>
                            </div>
                            <div id="grpBoxes" class="control-group">
                                <label class="control-label">Boxes children</label>
                                <div class="controls">
                                    <select id="ddlBoxChild" data-placeholder="Policy role" class="span6 select2_option" tabindex="0" multiple="multiple" name="ChildrenBoxesID" asp-items="@((List<SelectListItem>)ViewData["Boxes"])"><option value="0">Please select box</option></select>
                                </div>
                            </div>
                            <div class="control-group">
                                <label class="control-label">Description</label>
                                <div class="controls">
                                    <input type="text" name="Description" placeholder="Description" class="m-wrap large" />
                                    <span class="help-inline">Description</span>
                                </div>
                            </div>
                            <div class="form-actions">
                                <button type="submit" class="btn blue"><i class="icon-ok"></i> Save</button>
                                <button type="button" class="btn">Cancel</button>
                            </div>
                        </form>
                        <!-- END FORM-->
                    </div>
                </div>
            </div>
        </div>
        <!-- END PAGE CONTENT-->
    </div>
    <!-- END PAGE CONTAINER-->
</div>

src/CtrlBox.UI.Web/Views/Box/CreateBoxType.cshtml
@model CtrlBox.Application.ViewModel.BoxTypeVM

@{
    ViewData["Title"] = "CreateBoxType";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section cssViews{
    <link href="~/plugins/bootstrap-fileupload/bootstrap-fileupload.css" rel="stylesheet" type="text/css" />
    <link rel="stylesheet" type="text/css" href="~/plugins/select2/select2_metro.css" />
}
@section scriptsViews{
    <script type="text/javascript" src="~/plugins/select2/select2.min.js"></script>
    <script type="text/javascript" src="~/plugins/bootstrap-fileupload/bootstrap-fileupload.js"></script>
}

<script type="text/javascript">
    jQuery(document).ready(function () {
        $('.select2_option').select2({
            allowClear: true
        });

        $('#ddlLengthUnit').val('Centimeter');
        $('#ddlLengthUnit').trigger('change');
    });
</script>


<div class="page-content">
    <!-- BEGIN PAGE CONTAINER-->
    <div class="container-fluid">
        <!-- BEGIN PAGE HEADER-->
        <div class="row-fluid">
            <div class="span12">
                <ul class="breadcrumb">
                    <li>
                        <i class="icon-home"></i>
                        <a href="index.html">Address</a>
                        <span class="icon-angle-right"></span>
                    </li>
                    <li>
                        <a href="#">Index</a>
                        <span class="icon-angle-right"></span>
                    </li>
                    <li><a href="#">Create</a></li>
                </ul>
            </div>
        </div>
        <!-- END PAGE HEADER-->
        <!-- BEGIN PAGE CONTENT-->
        <div class="row-fluid">
            <div class="span12">
                <div class="portlet box blue">
                    <div class="portlet-title">
                        <div class="caption"><i class="icon-plus"></i>New BoxType</div>
                    </div>
                    <div class="portlet-body">
                        <!-- BEGIN FORM-->
                        <form asp-action="CreateBoxType" asp-controller="Box" enctype="multipart/form-data" class="form-horizontal">
                            <div class="control-group">
                                <label class="control-label">Name</label>
                                <div class="controls">
                                    <input id="cep" type="text" name="Name" placeholder="Name" class="m-wrap medium" />
                                    <span class="help-inline">Name</span>
                                </div>
                            </div>
                            <div class="control-group">
                                <label class="control-label">Description</label>
                                <div class="controls">
                                    <input id="rua" type="text" name="Description" placeholder="Description" class="m-wrap large" />
                                    <span class="help-inline">Description</span>
                                </div>
                            </div>
                            <div class="control-group">
                                <label class="control-label">Lenght</label>
                                <div class="controls">
                                    <input type="text" name="Lenght" placeholder="Lenght" class="m-wrap large" />
                                    <span class="help-inline">Lenght</span>
                                </div>
                            </div>
                            <div class="control-group">
                                <label class="control-label">Height</label>
                                <div class="controls">
                                    <input type="text" name="Height" placeholder="Height" class="m-wrap large" />
                                    <span class="help-inline">Height</span>
                                </div>
                            </div>
                            <div class="control-group">
                                <label class="control-label">Width</label>
                                <div class="controls">
                                    <input type="text" name="Width" placeholder="Width" class="m-wrap large" />
                                    <span class="help-inline">Width</span>
                                </div>
                            </div>
                            <div class="control-group">
                                <label class="control-label">LengthUnit</label>
                                <div class="controls">
                                    <select class="span6 select2_option" data-placeholder="Choose a Length" id="ddlLengthUnit" name="LengthUnit" asp-for="LengthUnit" asp-items="@((List<SelectListItem>)ViewData["OptionsBoxLengthUnit"])"></select>
                                </div>
                            </div>
                            <div class="control-group">
                                <label class="control-label">Is Returnable</label>
                                <div id="rdCashPayment" class="controls">
                                    <label class="radio">
                                        <input type="radio" name="IsReturnable" asp-for="IsReturnable" value="True" />
                                        Yes
                                    </label>
                                    <label class="radio">
                                        <input type="radio" name="IsReturnable" asp-for="IsReturnable" value="False" checked />
                                        No
                                    </label>
                                </div>
                            </div>
                            <div class="control-group">
                                <label class="control-label">MaxProductsItems</label>
                                <div class="controls">
                                    <input type="text" name="MaxProductsItems" placeholder="MaxProductsItems" class="m-wrap large" />
                                    <span class="help-inline">MaxProductsItems</span>
                                </div>
                            </div>
                            <partial name="~/Views/PartialsSections/_ViewUploadPicture.cshtml" />
                            <div class="form-actions">
                                <button type="submit" class="btn blue"><i class="icon-ok"></i> Save</button>
                                <button type="button" class="btn">Cancel</button>
                            </div>
                        </form>
                        <!-- END FORM-->
                    </div>
                </div>
            </div>
        </div>
        <!-- END PAGE CONTENT-->
    </div>
    <!-- END PAGE CONTAINER-->
</div>