src/CtrlBox.UI.Web/Controllers/ClientController.cs
using CtrlBox.Application.ViewModel;
using CtrlBox.CrossCutting;
using CtrlBox.CrossCutting.Enums;
using CtrlBox.Domain.Interfaces.Application;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Linq;

namespace CtrlBox.UI.Web.Controllers
{
    public class ClientController : Controller
    {
        private readonly IClientApplicationService _clientApplicationService;
        private readonly IAddressApplicationService _addressApplicationService;

        public ClientController(IClientApplicationService clientService, IAddressApplicationService addressApplicationService)
        {
            _clientApplicationService = clientService;
            _addressApplicationService = addressApplicationService;
        }

        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult AjaxHandlerGet()
        {
            var clients = _clientApplicationService.GetAll();
            return Json(new
            {
                aaData = clients
            });
        }

        public ActionResult Create(Guid clientID)
        {
            var clientVM = _clientApplicationService.GetById(clientID);

            if (clientVM != null)
                clientVM.SetClientsCategoriesID();

            LoadDropDowns();

            return View(clientVM);
        }

        private void LoadDropDowns()
        {
            var addresses = _addressApplicationService.GetAll()
                                        .Select(address => new SelectListItem
                                        {
                                            Value = address.DT_RowId,
                                            Text = $"{address.Street} - {address.Number} - {address.City} - {address.CEP}"
                                        }).ToList();
            ViewData["Addresses"] = addresses;

            var optionsTypes = _clientApplicationService.GetAllOptionsTypes()
                            .Select(option => new SelectListItem
                            {
                                Value = option.DT_RowId,
                                Text = $"{option.Name} - {option.EClientType}"
                            }).ToList();
            ViewData["OptionsTypes"] = optionsTypes;
        }

        [HttpPost]
        public ActionResult Create(ClientVM clientVM)
        {
            try
            {
                if (string.IsNullOrEmpty(clientVM.DT_RowId))
                    clientVM = _clientApplicationService.Add(clientVM);
                else
                    clientVM = _clientApplicationService.Update(clientVM);

                if (clientVM.HasNotifications)
                {
                    LoadDropDowns();
                    return View(clientVM);
                }

                return RedirectToAction("Index");
            }
            catch (CustomException exc)
            {
                throw exc;
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        [HttpPost]
        public ActionResult Edit(ClientVM clientVM)
        {
            _clientApplicationService.Update(clientVM);

            return Json(new
            {
                success = true,
                Message = "OK"
            });
        }

        public ActionResult OptionsTypes()
        {
            return View();
        }

        [HttpGet]
        public ActionResult GetAjaxHandlerOptionsTypes()
        {
            var optionsTypes = _clientApplicationService.GetAllOptionsTypes();
            return Json(new
            {
                aaData = optionsTypes
            });
        }

        public ActionResult CreateOptionType()
        {
            var clientsTypes = Enum.GetNames(typeof(EClientType))
                                        .Select(name => new SelectListItem
                                        {
                                            Value = name,
                                            Text = name
                                        }).ToList();
            ViewData["ClientsTypes"] = clientsTypes;

            return View();
        }

        [HttpPost]
        public ActionResult CreateOptionType(OptiontTypeVM optiontTypeVM)
        {
            _clientApplicationService.AddOptionType(optiontTypeVM);
            return RedirectToAction("OptionsTypes");
        }

    }
}

src/CtrlBox.UI.Web/Views/Shared/_LayoutClear.cshtml
<!DOCTYPE html>
<!--[if IE 8]> <html lang="en" class="ie8"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9"> <![endif]-->
<!--[if !IE]><!-->
<html lang="en">
 <!--<![endif]-->
<!-- BEGIN HEAD -->
<head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <title>CtrlBox | Login Page</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport" />
    <meta content="" name="description" />
    <meta content="" name="author" />
    <!-- BEGIN GLOBAL MANDATORY STYLES -->
    <link href="~/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/plugins/bootstrap/css/bootstrap-responsive.min.css" rel="stylesheet" type="text/css" />
    <link href="~/plugins/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
    <link href="~/css/style-metro.css" rel="stylesheet" type="text/css" />
    <link href="~/css/style.css" rel="stylesheet" type="text/css" />
    <link href="~/css/style-responsive.css" rel="stylesheet" type="text/css" />
    <link href="~/css/themes/default.css" rel="stylesheet" type="text/css" id="style_color" />
    <link href="~/plugins/uniform/css/uniform.default.css" rel="stylesheet" type="text/css" />
    <link rel="stylesheet" type="text/css" href="~/plugins/select2/select2_metro.css" />
    <!-- END GLOBAL MANDATORY STYLES -->
    <!-- BEGIN PAGE LEVEL STYLES -->
    <link href="~/css/pages/login.css" rel="stylesheet" type="text/css" />
    <!-- END PAGE LEVEL STYLES -->
    <link rel="shortcut icon" href="favicon.ico" />
    <!-- BEGIN JAVASCRIPTS(Load javascripts at bottom, this will reduce page load time) -->
    <!-- BEGIN CORE PLUGINS -->
    <script src="~/plugins/jquery-1.10.1.min.js" type="text/javascript"></script>
    <script src="~/plugins/jquery-migrate-1.2.1.min.js" type="text/javascript"></script>
    <!-- IMPORTANT! Load jquery-ui-1.10.1.custom.min.js before bootstrap.min.js to fix bootstrap tooltip conflict with jquery ui tooltip -->
    <script src="~/plugins/jquery-ui/jquery-ui-1.10.1.custom.min.js" type="text/javascript"></script>
    <script src="~/plugins/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
    <script src="~/plugins/bootstrap-hover-dropdown/twitter-bootstrap-hover-dropdown.min.js" type="text/javascript"></script>
    <!--[if lt IE 9]>
    <script src="~/plugins/excanvas.min.js"></script>
    <script src="~/plugins/respond.min.js"></script>
    <![endif]-->
    <script src="~/plugins/jquery-slimscroll/jquery.slimscroll.min.js" type="text/javascript"></script>
    <script src="~/plugins/jquery.blockui.min.js" type="text/javascript"></script>
    <script src="~/plugins/jquery.cookie.min.js" type="text/javascript"></script>
    <script src="~/plugins/uniform/jquery.uniform.min.js" type="text/javascript"></script>
    <!-- END CORE PLUGINS -->
    <!-- BEGIN PAGE LEVEL PLUGINS -->
    <script src="~/plugins/jquery-validation/dist/jquery.validate.min.js" type="text/javascript"></script>
    <script type="text/javascript" src="~/plugins/select2/select2.min.js"></script>
    <!-- END PAGE LEVEL PLUGINS -->
    <!-- BEGIN PAGE LEVEL SCRIPTS -->
    <script src="~/scripts/app.js" type="text/javascript"></script>
    <script src="~/scripts/login.js" type="text/javascript"></script>
    <!-- END PAGE LEVEL SCRIPTS -->
    <script>
		jQuery(document).ready(function() {
		  App.init();
		  Login.init();



		});
    </script>
    <!-- END JAVASCRIPTS -->
</head>
<!-- END HEAD -->
<!-- BEGIN BODY -->
<body class="login">
    @RenderBody()
    <!-- BEGIN COPYRIGHT -->
    <div class="copyright">
        2019 &copy; CtrlBox- Full control.
    </div>
    <!-- END COPYRIGHT -->

</body>
<!-- END BODY -->
</html>

src/CtrlBox.UI.Web/Views/Shared/_LayoutInvoice.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>CtrlBox - Invoice</title>

    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <meta name="description" content="CtrlBox - Invoice">
    <meta name="author" content="Juliano.Pestili">

    <link href="~/plugins/invoice/css/template.css" rel="stylesheet" />
</head>
<body>
    @RenderBody()
   
</body>
</html>

src/CtrlBox.UI.Web/Views/Shared/_MainMenu.cshtml
<ul class="sidebar-menu" data-widget="tree">
    <li class="header">HEADER</li>
    <!-- Optionally, you can add icons to the links -->
    <li class="treeview">
        <a href="#">
            <i class="fa fa-link"></i> <span>Registrations</span>
            <span class="pull-right-container">
                <i class="fa fa-angle-left pull-right"></i>
            </span>
        </a>
        <ul class="treeview-menu">
            <li>
                <a asp-controller="Client"
                   asp-action="Index">Clients</a>
            </li>
            <li><a href="#">Product</a></li>
            <li><a href="#">Route</a></li>
            <li><a href="#">Sale</a></li>
        </ul>
    </li>
    <li class="active"><a href="#"><i class="fa fa-link"></i> <span>Delivery</span></a></li>

</ul>